<?php

namespace ValueObjects\Metrology\UnitTypes\DigitalInformation;

use ValueObjects\Metrology\Observers\AbstractMetrologyObserver;
use ValueObjects\Metrology\Contracts\UnitTypes\DigitalInformation\DigitalInformationObserverInterface;

class AbstractDigitalInformationObserver extends AbstractMetrologyObserver implements DigitalInformationObserverInterface
{
}
